# Generated by Django 4.2.11 on 2024-10-05 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Simulator", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="useranswer", unique_together=set(),),
        migrations.AddField(
            model_name="useranswer",
            name="simulator_attempt",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="Simulator.simulatorattempt",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="useranswer", name="timestamp", field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together={("user", "simulator_attempt", "question")},
        ),
    ]
