# Generated by Django 4.2.11 on 2024-10-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Simulator", "0003_answeroption_hebrew_desc_question_hebrew_desc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="hebrew_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
