# Generated by Django 4.2.11 on 2024-10-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eng_word", models.CharField(max_length=50, unique=True)),
                ("heb_word", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "part_of_speech",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("sublist", models.IntegerField(blank=True, null=True)),
                ("example_sentence", models.TextField(blank=True, null=True)),
                ("usage_tips", models.TextField(blank=True, null=True)),
            ],
            options={"ordering": ["sublist", "eng_word"],},
        ),
    ]
