# Generated by Django 4.2.11 on 2024-10-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="word", name="is_root", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="word",
            name="example_sentence",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="part_of_speech",
            field=models.CharField(
                blank=True,
                choices=[
                    ("noun", "Noun"),
                    ("verb", "Verb"),
                    ("adjective", "Adjective"),
                    ("adverb", "Adverb"),
                    ("other", "Other"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="sublist",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="usage_tips",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
