# Generated by Django 4.2.11 on 2024-10-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Management", "0002_word_is_root_alter_word_example_sentence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word_Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eng_word", models.CharField(max_length=50, unique=True)),
                ("heb_word", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "part_of_speech",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("other", "Other"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "example_sentence",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("usage_tips", models.TextField(blank=True, default=None, null=True)),
                (
                    "root_word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Management.word",
                    ),
                ),
            ],
            options={"ordering": ["root_word", "eng_word"],},
        ),
    ]
