# Generated by Django 4.2.11 on 2024-10-31 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Management", "0004_word_source_word_word_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student_Word_Knowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "knowledge_level",
                    models.IntegerField(
                        choices=[(0, "○"), (1, "✓"), (2, "-"), (3, "✗")], default=0
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Management.word",
                    ),
                ),
            ],
            options={"unique_together": {("student", "word")},},
        ),
    ]
