# Generated by Django 4.2.11 on 2024-10-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Management", "0005_student_word_knowledge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_word_knowledge",
            name="knowledge_level",
            field=models.IntegerField(
                choices=[(0, "O"), (1, "✓"), (2, "-"), (3, "✗")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="word_level",
            field=models.IntegerField(
                choices=[(0, "O"), (1, "✓"), (2, "-"), (3, "✗")], default=0
            ),
        ),
    ]
