# Generated by Django 4.2.11 on 2024-10-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Management", "0006_alter_student_word_knowledge_knowledge_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_word_knowledge",
            name="selection_date",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
