# Generated by Django 4.2.11 on 2024-10-31 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Management", "0007_student_word_knowledge_selection_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student_word_knowledge",
            options={"ordering": ["student", "selection_date", "word"]},
        ),
        migrations.RenameField(
            model_name="student_word_knowledge",
            old_name="knowledge_level",
            new_name="familiarity",
        ),
    ]
