# Generated by Django 4.2.20 on 2025-06-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Management", "0008_alter_student_word_knowledge_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_word_knowledge",
            name="familiarity",
            field=models.IntegerField(choices=[(0, "O"), (1, "✓"), (2, "-"), (3, "✗")]),
        ),
    ]
