# Generated by Django 4.2.20 on 2025-06-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Management", "0009_alter_student_word_knowledge_familiarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="word", name="is_used", field=models.BooleanField(default=False),
        ),
    ]
