# Generated by Django 4.2.11 on 2024-09-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0002_chapter_question_simulator_simulatorattempt_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="chapter", unique_together=None,),
        migrations.RemoveField(model_name="chapter", name="simulator",),
        migrations.AlterUniqueTogether(name="question", unique_together=None,),
        migrations.RemoveField(model_name="question", name="chapter",),
        migrations.RemoveField(model_name="simulatorattempt", name="simulator",),
        migrations.RemoveField(model_name="simulatorattempt", name="user",),
        migrations.AlterUniqueTogether(name="useranswer", unique_together=None,),
        migrations.RemoveField(model_name="useranswer", name="question",),
        migrations.RemoveField(model_name="useranswer", name="selected_option",),
        migrations.RemoveField(model_name="useranswer", name="user",),
        migrations.DeleteModel(name="AnswerOption",),
        migrations.DeleteModel(name="Chapter",),
        migrations.DeleteModel(name="Question",),
        migrations.DeleteModel(name="Simulator",),
        migrations.DeleteModel(name="SimulatorAttempt",),
        migrations.DeleteModel(name="UserAnswer",),
    ]
